steps:
# Build ChatServer Container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/chatserver-image', './chatserver' ]

# Push updated ChatServer Container
- id: 'Push ChatServer image to registry'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/chatserver-image' ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=futurebank'
    
# Delete Existing Deployment 
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: [ 'delete', 'deployment', 'chatserver' ]
#  env:
#    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=futurebank'
    
# Deploy all in the Cloud
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: [ 'apply', '-f', 'cloudbuilder/chatserver-deployment.yaml' ]
#  env:
#    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=futurebank'
