---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "chatserver"
  namespace: "default"
  labels:
    app: "chatserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "chatserver"
  template:
    metadata:
      labels:
        app: "chatserver"
    spec:
      containers:
      - name: "chatserver-image"
        image: "gcr.io/gke-pipeline-savelee-192517/chatserver-image:latest"
        env:
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: "/var/run/secret/cloud.google.com/master.json"
          - name: "GCLOUD_PROJECT"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: GCLOUD_PROJECT
        volumeMounts:
          - mountPath: /var/run/secret/cloud.google.com/
            name: dialogflow
            readOnly: true
      volumes:
      - emptyDir: {}
        name: dialogflow
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "chatserver-hpa"
  namespace: "default"
  labels:
    app: "chatserver"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "chatserver"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
