apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "chatserver"
  namespace: "default"
  labels:
    app: "chatserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "chatserver"
  template:
    metadata:
      labels:
        app: "chatserver"
    spec:
      containers:
      - name: "chatserver-image"
        image: "gcr.io/gke-pipeline-savelee-192517/chatserver-image:latest"
        env:
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: /var/secrets/master.json
          - name: "GCLOUD_PROJECT"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: GCLOUD_PROJECT
          - name: "TOPIC"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TOPIC
          - name: "MY_CHATBASE_KEY"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: MY_CHATBASE_KEY
          - name: "MY_CHATBASE_VERSION"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: MY_CHATBASE_VERSION
        volumeMounts:
          - name: mykeys
            mountPath: /var/secrets/
            readOnly: true
        ports:
        - containerPort: 3000  
      volumes:
      - name: mykeys
        secret:
          secretName: credentials
