apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "chatserver"
  namespace: "default"
  labels:
    app: "chatserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "chatserver"
  template:
    metadata:
      labels:
        app: "chatserver"
    spec:
      containers:
      - name: "chatserver-image"
        image: "gcr.io/${PROJECT_ID}/chatserver-image:latest"
        imagePullPolicy: Always
        env:
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: /var/secrets/master.json
          - name: "GCLOUD_PROJECT"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: GCLOUD_PROJECT
          - name: "DEV_AGENT_PROJECT_ID"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: DEV_AGENT_PROJECT_ID
          - name: "TEST_AGENT_PROJECT_ID"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TEST_AGENT_PROJECT_ID
          - name: "TOPIC"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TOPIC
          - name: "MY_CHATBASE_KEY"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: MY_CHATBASE_KEY
          - name: "MY_CHATBASE_VERSION"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: MY_CHATBASE_VERSION
          - name: "MY_CHATBASE_BOT_NAME"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: "MY_CHATBASE_BOT_NAME"
          - name: "LANGUAGE_CODE"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: LANGUAGE_CODE
          - name: "GCLOUD_STORAGE_BUCKET_NAME"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: GCLOUD_STORAGE_BUCKET_NAME
          - name: "DATASET_TEST_METRICS"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: DATASET_TEST_METRICS
          - name: "TABLE"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TABLE
          - name: "DATASET"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: DATASET
          - name: "TABLE_TEST_METRICS"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TABLE_TEST_METRICS
        volumeMounts:
          - name: mykeys
            mountPath: /var/secrets/
            readOnly: true
        ports:
        - containerPort: 3000  
      volumes:
      - name: mykeys
        secret:
          secretName: credentials
