steps:
# Build ChatServer Container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/chatserver-image', './chatserver' ]

# Push updated ChatServer Container
- id: 'Push ChatServer image to registry'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/chatserver-image' ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
