steps:
# Build Django Container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/django-image', './server' ]

# Push updated Django Container
- id: 'Push Django image to registry'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/django-image' ]

# Delete Existing Deployment 
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'delete', 'deployment', 'django' ]

# Deploy all in the Cloud
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', 'cloudbuilder/django-deployment.yaml' ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=futurebank'