apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  clusterIP: 10.27.249.223
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    nodePort: 32041
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    nodePort: 31077
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-3
    nodePort: 31077
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-app
  sessionAffinity: None
  type: LoadBalancer